using OpCuriosidade.Entities.PersonnelContext;
using OpCuriosidade.Entities.PersonnelContext.ValueObjects;

namespace Application.Repositories.Migrations
{
    public class LoadPersons
    {
        public static void Load(List<Person> personsDB)
        {
            var staticPersons = new List<Person>
            {
                new Person("João Silva", "joao.silva@example.com", false, new DateOnly(1985, 5, 15), true, "Rua das Flores, 123, São Paulo",
                    new OtherInfos("Honestidade", "Feliz", "Cliente desde 2010", "Tecnologia"), new DateTime(2023, 3, 12, 8, 30, 0)),
                new Person("Maria Santos", "maria.santos@example.com", false, new DateOnly(1990, 8, 22), true, "Avenida Brasil, 456, Rio de Janeiro",
                    new OtherInfos("Respeito", "Motivada", "Preferência por e-mail", "Música"), new DateTime(2024, 1, 5, 14, 15, 0)),
                new Person("Carlos Oliveira", "carlos.oliveira@example.com", false, new DateOnly(1978, 3, 10), false, "Rua São Paulo, 789, Belo Horizonte",
                    new OtherInfos("Responsabilidade", null, "Solicitou newsletter", "Esportes"), new DateTime(2025, 7, 3, 9, 45, 0)),
                new Person("Ana Souza", "ana.souza@example.com", false, new DateOnly(1992, 11, 5), true, "Avenida Paulista, 1011, São Paulo",
                    new OtherInfos("Empatia", "Gratidão", null, "Leitura"), new DateTime(2024, 11, 18, 16, 20, 0)),
                new Person("Pedro Rodrigues", "pedro.rodrigues@example.com", false, new DateOnly(1988, 7, 30), true, "Rua do Comércio, 1314, Porto Alegre",
                    new OtherInfos("Trabalho em equipe", "Animado", "Indicado por amigo", "Viagens"), new DateTime(2025, 2, 28, 11, 10, 0)),
                new Person("Lucia Ferreira", "lucia.ferreira@example.com", false, new DateOnly(1975, 9, 18), false, "Avenida Central, 1516, Curitiba",
                    new OtherInfos(null, "Paz interior", "Cliente VIP", "Cinema"), new DateTime(2025, 7, 15, 13, 25, 0)),
                new Person("Bruno Lima", "bruno.lima@example.com", false, new DateOnly(1991, 6, 25), true, "Rua Bahia, 100, Salvador",
                    new OtherInfos("Persistência", "Confiante", "Novo cliente", "Culinária"), new DateTime(2023, 8, 7, 10, 5, 0)),
                new Person("Fernanda Costa", "fernanda.costa@example.com", false, new DateOnly(1983, 2, 19), true, "Rua das Laranjeiras, 78, Recife",
                    new OtherInfos("Autenticidade", "Animada", "Cliente recorrente", "Dança"), new DateTime(2024, 4, 22, 15, 30, 0)),
                new Person("Ricardo Almeida", "ricardo.almeida@example.com", false, new DateOnly(1970, 12, 12), false, "Avenida Maranhão, 456, Teresina",
                    new OtherInfos("Transparência", null, null, "Política"), new DateTime(2025, 6, 8, 12, 0, 0)),
                new Person("Juliana Rocha", "juliana.rocha@example.com", false, new DateOnly(1996, 4, 3), true, "Rua Ceará, 345, Fortaleza",
                    new OtherInfos("Lealdade", "Esperançosa", "Indicação", "Fotografia"), new DateTime(2025, 7, 22, 17, 45, 0)),
                new Person("Eduardo Martins", "eduardo.martins@example.com", false, new DateOnly(1984, 9, 8), false, "Avenida Amazonas, 213, Manaus",
                    new OtherInfos("Justiça", "Reflexivo", "Solicitou contato", "Astronomia"), new DateTime(2023, 12, 14, 9, 15, 0)),
                new Person("Patrícia Nogueira", "patricia.nogueira@example.com", false, new DateOnly(1993, 10, 29), true, "Rua Belém, 919, Belém",
                    new OtherInfos("Coragem", "Determinada", null, "Teatro"), new DateTime(2024, 7, 30, 14, 50, 0)),
                new Person("Tiago Mello", "tiago.mello@example.com", false, new DateOnly(1987, 11, 20), true, "Rua Piauí, 101, Goiânia",
                    new OtherInfos("Comprometimento", "Alegre", "Promoção ativa", "Séries"), new DateTime(2025, 1, 19, 8, 20, 0)),
                new Person("Camila Mendes", "camila.mendes@example.com", false, new DateOnly(1995, 1, 15), true, "Avenida Goiás, 606, Brasília",
                    new OtherInfos("Paixão", "Inspirada", "Interesse recente", "Moda"), new DateTime(2025, 7, 10, 10, 30, 0)),
                new Person("Anderson Souza", "anderson.souza@example.com", false, new DateOnly(1982, 5, 9), false, "Rua Tocantins, 321, Palmas",
                    new OtherInfos("Visão", null, "Antigo cliente", "Carros"), new DateTime(2023, 5, 21, 13, 10, 0)),
                new Person("Aline Ribeiro", "aline.ribeiro@example.com", false, new DateOnly(1997, 8, 18), true, "Rua Acre, 77, Boa Vista",
                    new OtherInfos("Paciência", "Contente", null, "Arquitetura"), new DateTime(2024, 9, 3, 16, 40, 0)),
                new Person("Roberta Cunha", "roberta.cunha@example.com", false, new DateOnly(1994, 3, 27), true, "Av. das Américas, 654, Florianópolis",
                    new OtherInfos("Gratidão", "Empolgada", "Fez curso", "Desenho"), new DateTime(2025, 3, 17, 11, 25, 0)),
                new Person("Vinícius Braga", "vinicius.braga@example.com", false, new DateOnly(1989, 7, 14), true, "Rua do Sol, 888, Natal",
                    new OtherInfos("Iniciativa", "Motivado", null, "Corrida"), new DateTime(2025, 7, 5, 9, 15, 0)),
                new Person("Natália Araújo", "natalia.araujo@example.com", false, new DateOnly(1981, 6, 3), false, "Rua São João, 1414, Maceió",
                    new OtherInfos(null, "Triste", "Quer suporte emocional", "Yoga"), new DateTime(2023, 10, 29, 14, 0, 0)),
                new Person("Henrique Lopes", "henrique.lopes@example.com", false, new DateOnly(1979, 12, 1), true, "Rua do Café, 212, São Luís",
                    new OtherInfos("Sinceridade", "Calmo", "Ligou recentemente", "Tecnologia"), new DateTime(2024, 2, 14, 10, 50, 0)),
                new Person("Letícia Carvalho", "leticia.carvalho@example.com", false, new DateOnly(1998, 10, 2), true, "Av. das Palmeiras, 343, João Pessoa",
                    new OtherInfos("Colaboração", "Feliz", null, "Natureza"), new DateTime(2025, 7, 18, 15, 10, 0)),
                new Person("Fábio Dias", "fabio.dias@example.com", false, new DateOnly(1986, 9, 11), true, "Rua dos Jacarandás, 515, Aracaju",
                    new OtherInfos("Determinação", null, "Contato por chat", "História"), new DateTime(2023, 7, 22, 8, 45, 0)),
                new Person("Sabrina Tavares", "sabrina.tavares@example.com", false, new DateOnly(1990, 1, 20), false, "Rua das Oliveiras, 118, Vitória",
                    new OtherInfos("Flexibilidade", "Entusiasmada", "Voltou a comprar", "Pintura"), new DateTime(2025, 4, 5, 12, 35, 0)),
                new Person("Rodrigo Fonseca", "rodrigo.fonseca@example.com", false, new DateOnly(1980, 4, 4), true, "Rua Paraná, 232, Campo Grande",
                    new OtherInfos("Compromisso", "Sereno", null, "Economia"), new DateTime(2024, 8, 19, 17, 20, 0)),
                new Person("Isabela Teixeira", "isabela.teixeira@example.com", false, new DateOnly(1991, 2, 23), true, "Av. dos Coqueiros, 400, Macapá",
                    new OtherInfos("Zelo", "Animada", "Feedback positivo", "Maquiagem"), new DateTime(2025, 7, 29, 14, 15, 0)),
                new Person("Marcelo Farias", "marcelo.farias@example.com", false, new DateOnly(1985, 7, 7), false, "Rua Maranhão, 303, Porto Velho",
                    new OtherInfos("Humildade", "Esperançoso", "Voltou recentemente", "Jogos"), new DateTime(2023, 9, 11, 11, 5, 0)),
                new Person("Gustavo Silva", "gustavo.silva@example.com", false, new DateOnly(1993, 12, 12), true, "Av. Central, 99, São Paulo",
                    new OtherInfos("Ambição", "Empolgado", null, "Negócios"), new DateTime(2024, 12, 24, 9, 30, 0)),
                new Person("Amanda Dias", "amanda.dias@example.com", false, new DateOnly(1996, 5, 5), true, "Rua 13 de Maio, 777, Campinas",
                    new OtherInfos("Confiança", "Sorridente", null, "Viagens"), new DateTime(2025, 5, 17, 16, 25, 0)),
                new Person("Felipe Souza", "felipe.souza@example.com", false, new DateOnly(1987, 3, 19), false, "Rua das Palmeiras, 1010, Osasco",
                    new OtherInfos("Foco", "Reservado", "Desativado", "Tecnologia"), new DateTime(2023, 11, 30, 13, 40, 0)),
                new Person("Cláudia Rocha", "claudia.rocha@example.com", false, new DateOnly(1982, 6, 30), true, "Rua da Independência, 303, Bauru",
                    new OtherInfos("Compreensão", "Gentil", "Atendimento elogiado", "Saúde"), new DateTime(2025, 7, 8, 10, 20, 0)),
                new Person("Rafael Mendes", "rafael.mendes@example.com", false, new DateOnly(1994, 8, 28), true, "Av. Brasil, 909, São Vicente",
                    new OtherInfos("Sabedoria", "Observador", "Avaliação positiva", "Robótica"), new DateTime(2024, 6, 13, 15, 15, 0)),
                new Person("Vanessa Lima", "vanessa.lima@example.com", false, new DateOnly(1988, 11, 16), true, "Rua Sete de Setembro, 606, Jundiaí",
                    new OtherInfos("Tolerância", "Pacífica", null, "Cinema"), new DateTime(2023, 4, 28, 14, 50, 0)),
                new Person("Douglas Costa", "douglas.costa@example.com", false, new DateOnly(1976, 9, 3), false, "Rua do Comércio, 222, Guarulhos",
                    new OtherInfos("Persistência", "Cético", null, "Esportes"), new DateTime(2025, 7, 1, 8, 10, 0)),
                new Person("Renata Almeida", "renata.almeida@example.com", false, new DateOnly(1990, 10, 10), true, "Rua Projetada, 808, Barueri",
                    new OtherInfos("Iniciativa", "Proativa", "Sugestão de melhorias", "Tecnologia"), new DateTime(2024, 5, 9, 12, 30, 0)),
                new Person("Lucas Gomes", "lucas.gomes@example.com", false, new DateOnly(1989, 2, 14), true, "Rua das Acácias, 123, Sorocaba",
                    new OtherInfos("Criatividade", "Inspirado", "Novo cadastro", "Música"), new DateTime(2025, 7, 12, 11, 45, 0)),
                new Person("Mariana Oliveira", "mariana.oliveira@example.com", false, new DateOnly(1992, 7, 8), false, "Av. das Rosas, 456, Ribeirão Preto",
                    new OtherInfos("Dedicação", "Concentrada", "Cliente inativo", "Arte"), new DateTime(2023, 6, 19, 9, 20, 0)),
                new Person("Gabriel Santos", "gabriel.santos@example.com", false, new DateOnly(1983, 4, 25), true, "Rua dos Lírios, 789, Santos",
                    new OtherInfos("Resiliência", "Determinado", "Frequente comprador", "Futebol"), new DateTime(2025, 3, 8, 14, 10, 0)),
                new Person("Beatriz Costa", "beatriz.costa@example.com", false, new DateOnly(1995, 9, 17), true, "Av. das Orquídeas, 101, São José dos Campos",
                    new OtherInfos("Organização", "Metódica", "Pediu orçamento", "Decoração"), new DateTime(2024, 10, 22, 16, 5, 0)),
                new Person("Leonardo Alves", "leonardo.alves@example.com", false, new DateOnly(1980, 11, 30), false, "Rua das Violetas, 202, Uberlândia",
                    new OtherInfos("Paciência", "Calmo", "Cadastro antigo", "Jardinagem"), new DateTime(2025, 7, 25, 10, 15, 0)),
                new Person("Carolina Rocha", "carolina.rocha@example.com", false, new DateOnly(1997, 3, 12), true, "Av. dos Girassóis, 303, Londrina",
                    new OtherInfos("Empatia", "Compreensiva", "Primeira compra", "Psicologia"), new DateTime(2023, 2, 28, 13, 30, 0)),
                new Person("Thiago Nunes", "thiago.nunes@example.com", false, new DateOnly(1987, 6, 19), true, "Rua das Hortênsias, 404, Joinville",
                    new OtherInfos("Proatividade", "Enérgico", "Comprou em promoção", "Tecnologia"), new DateTime(2025, 7, 17, 15, 40, 0)),
                new Person("Laura Mendonça", "laura.mendonca@example.com", false, new DateOnly(1993, 8, 5), false, "Av. das Margaridas, 505, Niterói",
                    new OtherInfos("Sensibilidade", "Artística", "Não respondeu pesquisa", "Pintura"), new DateTime(2024, 7, 14, 11, 20, 0)),
                new Person("Marcos Ribeiro", "marcos.ribeiro@example.com", false, new DateOnly(1978, 12, 22), true, "Rua dos Cravos, 606, Cuiabá",
                    new OtherInfos("Experiência", "Sábio", "Cliente fiel", "Vinhos"), new DateTime(2025, 1, 30, 9, 50, 0)),
                new Person("Tatiane Souza", "tatiane.souza@example.com", false, new DateOnly(1985, 5, 28), true, "Av. das Azaleias, 707, Feira de Santana",
                    new OtherInfos("Agilidade", "Dinâmica", "Recomendou produto", "Moda"), new DateTime(2023, 8, 17, 14, 25, 0)),
                new Person("Diego Martins", "diego.martins@example.com", false, new DateOnly(1991, 10, 11), false, "Rua das Begônias, 808, Juiz de Fora",
                    new OtherInfos("Precisão", "Detalhista", "Cancelou assinatura", "Fotografia"), new DateTime(2025, 7, 14, 12, 30, 0)),
                new Person("Viviane Lima", "viviane.lima@example.com", false, new DateOnly(1984, 1, 7), true, "Av. das Camélias, 909, Aracaju",
                    new OtherInfos("Diplomacia", "Paciente", "Participou de evento", "Relacionamentos"), new DateTime(2024, 3, 26, 10, 45, 0)),
                new Person("Alexandre Castro", "alexandre.castro@example.com", false, new DateOnly(1979, 7, 23), true, "Rua das Gardênias, 1010, Porto Alegre",
                    new OtherInfos("Liderança", "Carismático", "Assina newsletter", "Negócios"), new DateTime(2025, 7, 7, 16, 15, 0)),
                new Person("Simone Duarte", "simone.duarte@example.com", false, new DateOnly(1996, 2, 18), false, "Av. das Tulipas, 1111, Belém",
                    new OtherInfos("Intuição", "Perceptiva", "Baixa interação", "Astrologia"), new DateTime(2023, 10, 15, 13, 10, 0)),
                new Person("Roberto Andrade", "roberto.andrade@example.com", false, new DateOnly(1982, 9, 9), true, "Rua das Dálias, 1212, Goiânia",
                    new OtherInfos("Confiabilidade", "Pontual", "Cliente premium", "Finanças"), new DateTime(2025, 4, 18, 9, 30, 0)),
                new Person("Cristina Barbosa", "cristina.barbosa@example.com", false, new DateOnly(1975, 4, 30), true, "Av. dos Lírios, 1313, Florianópolis",
                    new OtherInfos("Sabedoria", "Experiente", "Desde o lançamento", "História"), new DateTime(2024, 11, 7, 15, 20, 0)),
                new Person("Daniel Torres", "daniel.torres@example.com", false, new DateOnly(1988, 12, 15), false, "Rua das Bromélias, 1414, Vitória",
                    new OtherInfos("Versatilidade", "Adaptável", "Contato esporádico", "Tecnologia"), new DateTime(2025, 7, 19, 14, 5, 0)),
                new Person("Elaine Costa", "elaine.costa@example.com", false, new DateOnly(1994, 6, 27), true, "Av. das Hortênsias, 1515, Manaus",
                    new OtherInfos("Otimismo", "Alegre", "Participa de promoções", "Viagens"), new DateTime(2023, 7, 8, 11, 35, 0)),
                new Person("José Pereira", "jose.pereira@example.com", false, new DateOnly(1973, 3, 8), false, "Rua das Violetas, 1616, Natal",
                    new OtherInfos("Tradição", "Conservador", "Cliente antigo", "Jornalismo"), new DateTime(2025, 2, 22, 10, 10, 0)),
                new Person("Adriana Freitas", "adriana.freitas@example.com", false, new DateOnly(1989, 8, 14), true, "Av. das Margaridas, 1717, Campo Grande",
                    new OtherInfos("Inovação", "Criativa", "Testou novo produto", "Design"), new DateTime(2024, 5, 14, 16, 50, 0)),
                new Person("Maurício Sampaio", "mauricio.sampaio@example.com", false, new DateOnly(1981, 1, 25), true, "Rua das Orquídeas, 1818, Teresina",
                    new OtherInfos("Estratégia", "Visionário", "Compra planejada", "Investimentos"), new DateTime(2025, 7, 28, 9, 25, 0)),
                new Person("Patrícia Monteiro", "patricia.monteiro@example.com", false, new DateOnly(1995, 5, 3), false, "Av. das Azaleias, 1919, João Pessoa",
                    new OtherInfos("Sensibilidade", "Empática", "Não renovou", "Literatura"), new DateTime(2023, 12, 19, 14, 15, 0)),
                new Person("Rogério Campos", "rogerio.campos@example.com", false, new DateOnly(1977, 10, 17), true, "Rua das Gardênias, 2020, Maceió",
                    new OtherInfos("Conhecimento", "Estudioso", "Compra técnica", "Ciência"), new DateTime(2024, 8, 3, 12, 40, 0)),
                new Person("Fernando Batista", "fernando.batista@example.com", false, new DateOnly(1986, 7, 9), true, "Av. das Tulipas, 2121, São Luís",
                    new OtherInfos("Dinamismo", "Ativo", "Compra frequente", "Esportes"), new DateTime(2025, 7, 23, 11, 15, 0)),
                new Person("Alessandra Vasconcelos", "alessandra.vasconcelos@example.com", false, new DateOnly(1992, 11, 20), false, "Rua das Dálias, 2222, Palmas",
                    new OtherInfos("Elegância", "Discreta", "Compra pontual", "Moda"), new DateTime(2023, 9, 26, 15, 30, 0)),
                new Person("Ricardo Mendonça", "ricardo.mendonca@example.com", false, new DateOnly(1983, 2, 12), true, "Av. dos Cravos, 2323, Porto Velho",
                    new OtherInfos("Persistência", "Determinado", "Cliente recorrente", "Negócios"), new DateTime(2025, 6, 11, 10, 20, 0)),
                new Person("Sandra Gomes", "sandra.gomes@example.com", false, new DateOnly(1974, 6, 28), true, "Rua das Begônias, 2424, Boa Vista",
                    new OtherInfos("Experiência", "Sábia", "Desde o início", "Educação"), new DateTime(2024, 4, 7, 13, 45, 0)),
                new Person("Hugo Teixeira", "hugo.teixeira@example.com", false, new DateOnly(1998, 9, 15), false, "Av. das Camélias, 2525, Macapá",
                    new OtherInfos("Curiosidade", "Aprendiz", "Cadastro recente", "Tecnologia"), new DateTime(2025, 7, 16, 14, 50, 0)),
                new Person("Luciana Andrade", "luciana.andrade@example.com", false, new DateOnly(1987, 4, 7), true, "Rua das Gardênias, 2626, Rio Branco",
                    new OtherInfos("Criatividade", "Inovadora", "Comprou novidade", "Arte"), new DateTime(2023, 11, 23, 9, 40, 0)),
                new Person("Gustavo Henrique", "gustavo.henrique@example.com", false, new DateOnly(1990, 12, 1), true, "Av. das Orquídeas, 2727, Vitória da Conquista",
                    new OtherInfos("Versatilidade", "Adaptável", "Compra variada", "Música"), new DateTime(2025, 7, 9, 16, 10, 0)),
                new Person("Carla Santana", "carla.santana@example.com", false, new DateOnly(1985, 8, 24), false, "Rua das Violetas, 2828, Petrolina",
                    new OtherInfos("Organização", "Metódica", "Não renovou", "Decoração"), new DateTime(2024, 2, 17, 11, 30, 0)),
                new Person("Rodrigo Pires", "rodrigo.pires@example.com", false, new DateOnly(1979, 3, 19), true, "Av. das Margaridas, 2929, Juazeiro do Norte",
                    new OtherInfos("Conhecimento", "Estudioso", "Cliente fiel", "Literatura"), new DateTime(2025, 7, 27, 10, 45, 0)),
                new Person("Vanessa Souza", "vanessa.souza@example.com", false, new DateOnly(1993, 7, 11), true, "Rua das Azaleias, 3030, Mossoró",
                    new OtherInfos("Empatia", "Compreensiva", "Feedback positivo", "Psicologia"), new DateTime(2023, 5, 12, 14, 20, 0)),
                new Person("Felipe Costa", "felipe.costa@example.com", false, new DateOnly(1988, 1, 30), false, "Av. dos Girassóis, 3131, Caxias do Sul",
                    new OtherInfos("Agilidade", "Dinâmico", "Baixa interação", "Esportes"), new DateTime(2025, 7, 4, 15, 35, 0)),
                new Person("Larissa Martins", "larissa.martins@example.com", false, new DateOnly(1996, 10, 22), true, "Rua das Hortênsias, 3232, Blumenau",
                    new OtherInfos("Sensibilidade", "Artística", "Nova cliente", "Pintura"), new DateTime(2024, 9, 28, 12, 15, 0)),
                new Person("Marcelo Augusto", "marcelo.augusto@example.com", false, new DateOnly(1976, 5, 14), true, "Av. das Tulipas, 3333, Pelotas",
                    new OtherInfos("Experiência", "Sábio", "Cliente desde 2005", "Vinhos"), new DateTime(2025, 7, 20, 9, 55, 0)),
                new Person("Tânia Ribeiro", "tania.ribeiro@example.com", false, new DateOnly(1984, 12, 5), false, "Rua das Dálias, 3434, Canoas",
                    new OtherInfos("Elegância", "Discreta", "Não respondeu pesquisa", "Moda"), new DateTime(2023, 8, 30, 13, 25, 0)),
                new Person("Sérgio Nascimento", "sergio.nascimento@example.com", false, new DateOnly(1972, 9, 28), true, "Av. das Begônias, 3535, Bauru",
                    new OtherInfos("Persistência", "Determinado", "Cliente premium", "Negócios"), new DateTime(2024, 7, 16, 16, 45, 0)),
                new Person("Helena Fernandes", "helena.fernandes@example.com", false, new DateOnly(1997, 2, 9), true, "Rua das Camélias, 3636, Piracicaba",
                    new OtherInfos("Curiosidade", "Aprendiz", "Primeira compra", "Tecnologia"), new DateTime(2025, 7, 11, 10, 30, 0)),
                new Person("Paulo Roberto", "paulo.roberto@example.com", false, new DateOnly(1981, 6, 23), false, "Av. das Gardênias, 3737, Uberaba",
                    new OtherInfos("Criatividade", "Inovador", "Cadastro inativo", "Arte"), new DateTime(2023, 4, 17, 14, 10, 0)),
                new Person("Mônica Alencar", "monica.alencar@example.com", false, new DateOnly(1994, 8, 16), true, "Rua das Orquídeas, 3838, Cascavel",
                    new OtherInfos("Versatilidade", "Adaptável", "Compra variada", "Música"), new DateTime(2025, 7, 26, 12, 50, 0)),
                new Person("Renato Silva", "renato.silva@example.com", false, new DateOnly(1989, 3, 7), true, "Av. das Violetas, 3939, Franca",
                    new OtherInfos("Organização", "Metódico", "Cliente recorrente", "Decoração"), new DateTime(2024, 1, 21, 9, 20, 0)),
                new Person("Daniela Costa", "daniela.costa@example.com", false, new DateOnly(1978, 11, 19), false, "Rua das Margaridas, 4040, Ponta Grossa",
                    new OtherInfos("Conhecimento", "Estudiosa", "Não renovou", "Literatura"), new DateTime(2025, 7, 13, 15, 15, 0)),
                new Person("Alexandre Moraes", "alexandre.moraes@example.com", false, new DateOnly(1983, 7, 2), true, "Av. das Azaleias, 4141, Guarujá",
                    new OtherInfos("Empatia", "Compreensivo", "Feedback positivo", "Psicologia"), new DateTime(2023, 10, 8, 11, 45, 0)),
                new Person("Cintia Rocha", "cintia.rocha@example.com", false, new DateOnly(1995, 4, 27), true, "Rua dos Girassóis, 4242, Praia Grande",
                    new OtherInfos("Agilidade", "Dinâmica", "Nova cliente", "Esportes"), new DateTime(2025, 7, 24, 14, 25, 0)),
                new Person("Roberval Santos", "roberval.santos@example.com", false, new DateOnly(1975, 1, 14), true, "Av. das Hortênsias, 4343, Petrópolis",
                    new OtherInfos("Experiência", "Sábio", "Cliente desde 2000", "Vinhos"), new DateTime(2024, 6, 30, 10, 10, 0)),
                new Person("Viviane Castro", "viviane.castro@example.com", false, new DateOnly(1987, 10, 8), false, "Rua das Tulipas, 4444, Limeira",
                    new OtherInfos("Elegância", "Discreta", "Baixa interação", "Moda"), new DateTime(2025, 7, 6, 16, 40, 0)),
                new Person("Marcos Vinicius", "marcos.vinicius@example.com", false, new DateOnly(1992, 5, 21), true, "Av. das Dálias, 4545, Taubaté",
                    new OtherInfos("Persistência", "Determinado", "Compra planejada", "Negócios"), new DateTime(2023, 7, 19, 13, 30, 0)),
                new Person("Leticia Mendes", "leticia.mendes@example.com", false, new DateOnly(1998, 12, 3), true, "Rua das Begônias, 4646, Rio Verde",
                    new OtherInfos("Curiosidade", "Aprendiz", "Primeira compra", "Tecnologia"), new DateTime(2025, 7, 21, 9, 50, 0))
            };

            personsDB.AddRange(staticPersons);
        }
    }
}